### ISSUE TITLE
The Checkout URL should not be the same as the Confirmation URL

### ISSUE THREAD

**Issue by mattias-sanfridsson** [MyOnlineStore/omnipay-klarna-checkout#53]
In the Merchant URLs array, the checkout- and confirmation-urls are currently given the same value (the returnUrl parameter). However, the [Klarna documentation](https://developers.klarna.com/api/#checkout-api__ordermerchant_urls__checkout) specifically states that these should differ.

I'll open a PR shortly that allows you to provide a specific confirmation URL.

**Comment by Feijs** [comment]
Resolved with #54, released in v3.0.4
Thanks for fixing @mattias-persson
