### ISSUE TITLE
Would you consider adding a LICENSE?

### ISSUE THREAD

**Issue by markjeffries** [MyOnlineStore/omnipay-klarna-checkout#58]
Hi,

I'd really like to use this library, would you consider adding a LICENSE file so it can be used for commercial purposes?

Perhaps a standard [MIT license](https://opensource.org/licenses/MIT)?

Thanks!

**Comment by digibeuk** [comment]
Hi Mark,

composer lists the license as MIT, we could add it to the README also!

**Comment by markjeffries** [comment]
Ah didn't spot that, thanks!
