### ISSUE TITLE
No option to provide shipping options

### ISSUE THREAD

**Issue by robjmills** [MyOnlineStore/omnipay-klarna-checkout#60]
Hi,

It appears that there's currently no way to provide shipping options when creating a new order [as outlined here](https://developers.klarna.com/api/#checkout-api-create-a-new-order). The order object should allow for a `shipping_options` key, which can then be passed to Klarna to allow the user to select the chosen option within the initial Klarna checkout UI. If one is provided, it's currently stripped out by the `validate` call in `\MyOnlineStore\Omnipay\KlarnaCheckout\Message\AuthorizeRequest::getData`

Is this possible using an alternate method? If not, are you open to a PR to add this?

**Comment by Feijs** [comment]
I don't believe this can be done currently. It is functionality we do not actively use. If you would be willing to add the option, that would be welcome!

**Comment by robjmills** [comment]
ok great, i'll be working on that this week so hopefully i'll have a PR for you to look at soon.

**Comment by robjmills** [comment]
sorry i've had to shelve this work for now
